name: Production
on:
  push:
    # branches:
    #   - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10'

      - uses: actions/cache@v2
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install
      - run: yarn build_production

      - uses: actions/upload-artifact@v2
        with:
          name: dists-production
          path: build/

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.QUAY_IO_BOT_USERNAME }}
          password: ${{ secrets.QUAY_IO_BOT_PASSWORD }}
          registry: quay.io
          repository: ${{ github.repository }}
          tag_with_sha: true
          add_git_labels: true

      - name: Trigger deployment
        env:
          DEPLOY_PHASE: production
        run: |
          export IMAGE_TAG=$(echo "sha-$GITHUB_SHA" | cut -c -11)
          export DESCRIPTION="GitHub Actions Context:
          * Run ID: ${{ github.run_id }}
          * Commit: ${{ github.sha }}
          * Ref: ${{ github.ref }}
          "
          curl -fsSL -w "%{http_code}" -X POST \
            -F "token=${{ secrets.ITERING_DEPLOYMENT_TRIGGER_TOKEN }}" \
            -F "ref=master" \
            -F "variables[DEPLOY_PHASE]=$DEPLOY_PHASE" \
            -F "variables[DEPLOY_PROJECT]=${{ github.repository }}" \
            -F "variables[DEPLOY_IMAGE_TAG]=$IMAGE_TAG" \
            -F "variables[DEPLOY_DESCRIPTION]=$DESCRIPTION" \
            "${{ secrets.ITERING_DEPLOYMENT_TRIGGER_ENDPOINT }}"
