name: Production
on:
  push:
    # branches:
    #   - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10'

      - id: yarn_cache_dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn_cache_dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-production-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-production-

      - run: yarn install
      - run: yarn build_production

      - uses: actions/upload-artifact@v2
        with:
          name: dists-production
          path: build/

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.QUAY_IO_BOT_USERNAME }}
          password: ${{ secrets.QUAY_IO_BOT_PASSWORD }}
          registry: quay.io
          repository: darwinia-network/bridge-apps
          tag_with_sha: true
          add_git_labels: true

      - id: docker_image
        # See: https://github.com/docker/github-actions/blob/0f18e2abad9a4ac2963d2516246787375b5ec917/internal/options/tag.go#L87
        run: echo "::set-output name=sha_tag::$(echo "sha-$GITHUB_SHA" | cut -c -11)"
